server:
  port: 9090

spring:
  application:
    name: account-book-server
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/account_book?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 12345678
      auto-commit: true
      connection-test-query: select 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 8
      minimum-idle: 8
      pool-name: HikariCP-financial